# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('page', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('locate_product', models.BooleanField(default=False)),
                ('locate_collection', models.BooleanField(default=False)),
                ('locate_manafactur', models.BooleanField(default=False)),
                ('send_project', models.BooleanField(default=False)),
                ('send_project_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('buy', models.BooleanField(default=False)),
                ('buy_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Слежение посещения',
                'verbose_name_plural': 'Слежение посещения',
            },
        ),
        migrations.CreateModel(
            name='Log_In_Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('leng', models.CharField(blank=True, default=None, max_length=3, null=True)),
            ],
            options={
                'verbose_name': 'Статистика нахождения пользователей на сайте',
                'verbose_name_plural': 'Статистика нахождения пользователей на сайте',
            },
        ),
        migrations.CreateModel(
            name='Send_Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_send', models.TextField(blank=True, default=None, null=True)),
                ('order_img', models.FileField(upload_to='shadow_orders/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User_Login')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'verbose_name': 'Сообщения - ордер',
                'verbose_name_plural': 'Сообщения - ордер',
            },
        ),
        migrations.CreateModel(
            name='Send_Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_send', models.TextField(blank=True, default=None, null=True)),
                ('project_img', models.FileField(upload_to='shadow_projects/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.User_Login')),
                ('project', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Find_Project')),
            ],
            options={
                'verbose_name': 'Сообщения - проект',
                'verbose_name_plural': 'Сообщения - проект',
            },
        ),
        migrations.CreateModel(
            name='Statistic_Find_Bloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('collection', models.TextField(blank=True, default=None, null=True)),
                ('page', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Статистика блочного поиска',
                'verbose_name_plural': 'Статистика блочного поиска',
            },
        ),
        migrations.CreateModel(
            name='Statistic_Find_Simple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('find_collections', models.TextField(blank=True, default=None, null=True)),
                ('find_manafacturer', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Статистика простого поиска',
                'verbose_name_plural': 'Статистика простого поиска',
            },
        ),
        migrations.CreateModel(
            name='Statistic_User_Sing_In_ColProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('collection', models.TextField(blank=True, default=None, null=True)),
                ('collection_product', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Статистика перехода в коллекцию или продукт',
                'verbose_name_plural': 'Статистика перехода в коллекцию или продукт',
            },
        ),
        migrations.AddField(
            model_name='eye',
            name='log_in_site',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shadow.Log_In_Site'),
        ),
    ]
