# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Call_Me',
        ),
    ]
