# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_delete_call_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call_Me',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_me_name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('call_me_phone', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Перезвоните мне',
                'verbose_name_plural': 'Перезвоните мне',
            },
        ),
    ]
