# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_availability', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('name_availability_ukr', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Availability (Наличие)',
                'verbose_name_plural': 'Availabilitys (Наличие)',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_collection', models.BooleanField(default=True)),
                ('is_view_main', models.BooleanField(default=False)),
                ('name_collection', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('price_download', models.FileField(default=None, null=True, upload_to='price_download/')),
                ('description_collection', models.TextField(blank=True, default=None, null=True)),
                ('description_collection_ukr', models.TextField(blank=True, default=None, null=True)),
                ('short_description_collection', models.TextField(blank=True, default=None, null=True)),
                ('short_description_collection_ukr', models.TextField(blank=True, default=None, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=320, null=True)),
                ('title_ukr', models.CharField(blank=True, default=None, max_length=320, null=True)),
                ('keyword', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('keyword_ukr', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('description_ukr', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('availability_collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Availability')),
            ],
            options={
                'verbose_name': 'Collection (Коллекция)',
                'verbose_name_plural': 'Collections (Коллекции)',
            },
        ),
        migrations.CreateModel(
            name='Collection_Application_For_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_application_is_active', models.BooleanField(default=True)),
                ('collection_application_bathrooms', models.BooleanField(default=False)),
                ('collection_application_floor', models.BooleanField(default=False)),
                ('collection_application_apron', models.BooleanField(default=False)),
                ('collection_application_outdoor', models.BooleanField(default=False)),
                ('collection_application_residential', models.BooleanField(default=False)),
                ('collection_application_projects', models.BooleanField(default=False)),
                ('name_collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name': 'Collection_Application_Search (Применение)',
                'verbose_name_plural': 'Collection_Application_Search (Применения)',
            },
        ),
        migrations.CreateModel(
            name='Collection_Colour_For_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_colour_is_active', models.BooleanField(default=True)),
                ('collection_colour_beige', models.BooleanField(default=False)),
                ('collection_colour_white', models.BooleanField(default=False)),
                ('collection_colour_burgundy', models.BooleanField(default=False)),
                ('collection_colour_blue', models.BooleanField(default=False)),
                ('collection_colour_yellow', models.BooleanField(default=False)),
                ('collection_colour_green', models.BooleanField(default=False)),
                ('collection_colour_gold', models.BooleanField(default=False)),
                ('collection_colour_brown', models.BooleanField(default=False)),
                ('collection_colour_red', models.BooleanField(default=False)),
                ('collection_colour_multicolor', models.BooleanField(default=False)),
                ('collection_colour_orange', models.BooleanField(default=False)),
                ('collection_colour_pink', models.BooleanField(default=False)),
                ('collection_colour_silver_platinum', models.BooleanField(default=False)),
                ('collection_colour_silver_grey', models.BooleanField(default=False)),
                ('collection_colour_silver_darkblue', models.BooleanField(default=False)),
                ('collection_colour_silver_lilac', models.BooleanField(default=False)),
                ('collection_colour_silver_black', models.BooleanField(default=False)),
                ('name_colour_collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name': 'Collection_Colour_For_Search (Цвет)',
                'verbose_name_plural': 'Collection_Colour_For_Search (Цвета)',
            },
        ),
        migrations.CreateModel(
            name='Collection_Facturer_For_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_facturer_is_active', models.BooleanField(default=True)),
                ('collection_stile_glossy', models.BooleanField(default=False)),
                ('collection_stile_matte', models.BooleanField(default=False)),
                ('collection_stile_polished', models.BooleanField(default=False)),
                ('collection_stile_polopolarized', models.BooleanField(default=False)),
                ('collection_stile_satin', models.BooleanField(default=False)),
                ('collection_stile_aged', models.BooleanField(default=False)),
                ('collection_stile_structured', models.BooleanField(default=False)),
                ('name_facturer_collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name': 'Collection_Facturer_For_Search (Фактура)',
                'verbose_name_plural': 'Collection_Facturer_For_Search (Фактуры)',
            },
        ),
        migrations.CreateModel(
            name='Collection_Floor_For_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_floor_is_active', models.BooleanField(default=True)),
                ('collection_floor_floor', models.BooleanField(default=False)),
                ('collection_floor_wall', models.BooleanField(default=False)),
                ('collection_floor_universal', models.BooleanField(default=False)),
                ('name_floor_collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name': 'Collection_Floor_For_Search (Настенная/Напольная)',
                'verbose_name_plural': 'Collection_Floor_For_Search (Настенная/Напольная)',
            },
        ),
        migrations.CreateModel(
            name='Collection_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_collection', models.ImageField(upload_to='collection_images/')),
                ('is_main_collection', models.BooleanField(default=False)),
                ('is_active_collection', models.BooleanField(default=True)),
                ('name_collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name': 'Collection_Image (Изображение в коллекции)',
                'verbose_name_plural': 'Collection_Images (Изображения в коллекциях)',
            },
        ),
        migrations.CreateModel(
            name='Collection_Search_NHS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_collection_nhs', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('name_collection_nhs_ukr', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Collection_Search_NHS (Новинка_Хит_Распродажа)',
                'verbose_name_plural': 'Collection_Search_NHSs (Новинка_Хит_Распродажа)',
            },
        ),
        migrations.CreateModel(
            name='Collection_Style_For_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_stile_is_active', models.BooleanField(default=True)),
                ('collection_stile_vintage', models.BooleanField(default=False)),
                ('collection_stile_classic', models.BooleanField(default=False)),
                ('collection_stile_modern', models.BooleanField(default=False)),
                ('name_style_collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name': 'Collection_Style_For_Search (Стиль)',
                'verbose_name_plural': 'Collection_Style_For_Search (Стили)',
            },
        ),
        migrations.CreateModel(
            name='Collection_Texturer_For_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_texturer_is_active', models.BooleanField(default=True)),
                ('collection_texturer_3d', models.BooleanField(default=False)),
                ('collection_texturer_art', models.BooleanField(default=False)),
                ('collection_texturer_concrete', models.BooleanField(default=False)),
                ('collection_texturer_geometrical', models.BooleanField(default=False)),
                ('collection_texturer_damaskato', models.BooleanField(default=False)),
                ('collection_texturer_wood', models.BooleanField(default=False)),
                ('collection_texturer_imitationbrick', models.BooleanField(default=False)),
                ('collection_texturer_imitationskin', models.BooleanField(default=False)),
                ('collection_texturer_rock', models.BooleanField(default=False)),
                ('collection_texturer_cotto', models.BooleanField(default=False)),
                ('collection_texturer_crackle', models.BooleanField(default=False)),
                ('collection_texturer_metal', models.BooleanField(default=False)),
                ('collection_texturer_monocolor', models.BooleanField(default=False)),
                ('collection_texturer_marble', models.BooleanField(default=False)),
                ('collection_texturer_onyx', models.BooleanField(default=False)),
                ('collection_texturer_patchwork', models.BooleanField(default=False)),
                ('collection_texturer_cloth', models.BooleanField(default=False)),
                ('collection_texturer_travertine', models.BooleanField(default=False)),
                ('collection_texturer_flowers', models.BooleanField(default=False)),
                ('collection_texturer_ethnic', models.BooleanField(default=False)),
                ('name_texturer_collection', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name': 'Collection_Texturer_For_Search (Текстура)',
                'verbose_name_plural': 'Collection_Texturer_For_Search (Текстуры)',
            },
        ),
        migrations.CreateModel(
            name='Collection_Type_Material_For_Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_type_material_is_active', models.BooleanField(default=True)),
                ('collection_type_material_grout', models.BooleanField(default=False)),
                ('collection_type_material_ceramic', models.BooleanField(default=False)),
                ('collection_type_material_porcelain', models.BooleanField(default=False)),
                ('collection_type_material_clinker', models.BooleanField(default=False)),
                ('collection_type_material_natural', models.BooleanField(default=False)),
                ('collection_type_material_leveling', models.BooleanField(default=False)),
                ('collection_type_material_glass', models.BooleanField(default=False)),
                ('collection_type_material_steps', models.BooleanField(default=False)),
                ('name_collection_type_material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name': 'Collection_Type_Material_Search (Тип материала)',
                'verbose_name_plural': 'Collection_Type_Material_Search (Типы материалов)',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_manufacturer', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('image_logo_manufacturer', models.ImageField(upload_to='manufacturer_images_logo/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description_manufacturer', models.TextField(blank=True, default=None, null=True)),
                ('description_manufacturer_ukr', models.TextField(blank=True, default=None, null=True)),
                ('short_description_manufacturer', models.TextField(blank=True, default=None, null=True)),
                ('short_description_manufacturer_ukr', models.TextField(blank=True, default=None, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=320, null=True)),
                ('title_ukr', models.CharField(blank=True, default=None, max_length=320, null=True)),
                ('keyword', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('keyword_ukr', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('description_ukr', models.CharField(blank=True, default=None, max_length=512, null=True)),
            ],
            options={
                'verbose_name': 'Manufacturer (Производитель)',
                'verbose_name_plural': 'Manufacturers (Производители)',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer_Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_manufacturer_country', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('name_manufacturer_country_ukr', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Manufacturer_Country (Страна производитель)',
                'verbose_name_plural': 'Manufacturer_Countrys (Страны призводителей)',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_manufacturer', models.ImageField(upload_to='manufacturer_images/')),
                ('is_active_manufacturer', models.BooleanField(default=True)),
                ('name_manufacturer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Manufacturer')),
            ],
            options={
                'verbose_name': 'Manufacturer_Image (Изображение в производителе)',
                'verbose_name_plural': 'Manufacturer_Images (Изображения в производителе)',
            },
        ),
        migrations.CreateModel(
            name='Price_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_price_group', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Price_Group (Ценовая группв)',
                'verbose_name_plural': 'Price_Groups (Ценовые группы)',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('vendor_code_product', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, default=None, max_length=320, null=True)),
                ('title_ukr', models.CharField(blank=True, default=None, max_length=320, null=True)),
                ('keyword', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('keyword_ukr', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('description_ukr', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('collection_product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name': 'Product (Продукт)',
                'verbose_name_plural': 'Products (Продукты)',
            },
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name': 'Product_Image (Изображение продукта)',
                'verbose_name_plural': 'Product_Images (Изображения продуктов)',
            },
        ),
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product_type', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('name_product_type_ukr', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('yacor', models.CharField(blank=True, default=None, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Product_Type (Тип продукта)',
                'verbose_name_plural': 'Product_Type (Типы продуктов)',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_size', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
            options={
                'verbose_name': 'Size (Размер)',
                'verbose_name_plural': 'Sizes (Размеры)',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product_Type'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Size'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='manufacturer_country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Manufacturer_Country'),
        ),
        migrations.AddField(
            model_name='collection',
            name='manufacturer_collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Manufacturer'),
        ),
        migrations.AddField(
            model_name='collection',
            name='name_collection_nhs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Collection_Search_NHS'),
        ),
        migrations.AddField(
            model_name='collection',
            name='price_group_collection',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Price_Group'),
        ),
    ]
