# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-20 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171020_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='image_mini',
            field=models.ImageField(default=None, null=True, upload_to='products_images_mini/'),
        ),
    ]
