# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171023_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_collection_mini',
            field=models.ImageField(default=None, null=True, upload_to='collection_images_mini/'),
        ),
    ]
