# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_collection_image_collection_mini'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data_target',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
