# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-08 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_data_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='id_patch',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
